const $ = (id) => document.getElementById(id);
const state = {
  connected:false, context:null, job:null, imagery:null, tileManifest:null,
  rankings:[], selected:null, match:null, validation:null, review:null,
  searchLayer:null, tileLayer:null, tileImage:null, checkpointMode:false, checkpoints:[],
};

if (!globalThis.L) throw new Error("Leaflet failed to load");
const map = L.map("reviewMap", {zoomControl:false}).setView([39,-97],4);
L.control.zoom({position:"topright"}).addTo(map);
const streets = L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {maxZoom:20, attribution:"&copy; OpenStreetMap contributors"}).addTo(map);
const satellite = L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}", {maxZoom:20, attribution:"Tiles &copy; Esri and imagery partners"});
L.control.layers({"Street map":streets,"Satellite imagery":satellite},{},{position:"topright"}).addTo(map);
const checkpointLayer = L.layerGroup().addTo(map);

function apiBase(){return $("apiUrl").value.trim().replace(/\/$/,"")}
function log(message,data=null){const stamp=new Date().toISOString();$("auditLog").textContent=`${stamp}  ${message}${data?`\n${JSON.stringify(data,null,2)}`:""}\n\n${$("auditLog").textContent}`}
function parse(id,fallback=null){try{return JSON.parse($(id).value)}catch(error){throw new Error(`${id}: ${error.message}`)}}
function fileUrl(path){return `${apiBase()}/file?path=${encodeURIComponent(path)}`}
async function request(path, options={}){
  const response=await fetch(`${apiBase()}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});
  let payload={};try{payload=await response.json()}catch{}
  if(!response.ok)throw new Error(payload.detail||`${response.status} ${response.statusText}`);
  return payload;
}
async function action(label,fn){try{const result=await fn();log(label,result);return result}catch(error){log(`${label} failed`,{error:error.message});alert(error.message);throw error}}
function download(name,value,type="application/json") {const blob=value instanceof Blob?value:new Blob([typeof value==="string"?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function setConnection(ok,message){state.connected=ok;$("connectionStatus").className=`connection ${ok?"online":"offline"}`;$("connectionStatus").textContent=message;$("localWorkerHelp").hidden=ok}
function renderJob(payload){state.job=payload.job||payload;const job=state.job;$("jobId").value=job.job_id;$("jobState").innerHTML=`<strong>${job.state}</strong> · ${job.job_id}\n${job.search_polygons?.length||0} bounded search polygon(s) · ${Object.values(job.artifacts||{}).flat().length} artifact(s)`}
function renderContext(context){state.context=context;const f=context.formation;$("formationId").value=f.formation_id;$("dateStart").value=(f.date_iso||"").slice(0,10);$("dateEnd").value=(f.date_iso||"").slice(0,10);$("formationContext").textContent=`${f.date_iso||"undated"} — ${f.place||"unnamed"}, ${f.region||""}, ${f.country||""}\nSpatial role: ${context.locality.role||"unresolved"}\nAssertions: ${context.source_assertion_ids.join(", ")}\n${context.locality.warning}\n\n${context.source_assertions.map(a=>`${a.source_name}: ${a.source_record_url||a.source_url}`).join("\n")}`;if(f.latitude&&f.longitude)map.setView([Number(f.latitude),Number(f.longitude)],12)}
function polygonFromBounds(){const b=map.getBounds();return {type:"Polygon",coordinates:[[[b.getWest(),b.getSouth()],[b.getEast(),b.getSouth()],[b.getEast(),b.getNorth()],[b.getWest(),b.getNorth()],[b.getWest(),b.getSouth()]]]}}
function showSearchPolygon(geometry){if(state.searchLayer)state.searchLayer.remove();state.searchLayer=L.geoJSON(geometry,{style:{color:"#58d9c4",weight:3,dashArray:"8 6",fillOpacity:.06}}).addTo(map);map.fitBounds(state.searchLayer.getBounds(),{padding:[30,30]})}
function renderImagery(payload){state.imagery=payload;const select=$("imageryVintage");select.innerHTML="";payload.items.forEach((item,index)=>{const option=document.createElement("option");option.value=String(index);option.textContent=`${item.acquisition.start||"undated"} · ${item.provider} · ${item.collection}/${item.item_id}`;select.append(option)});if(!payload.items.length)select.innerHTML="<option>No imagery matched</option>"}
function selectedImagery(){return state.imagery?.items?.[Number($("imageryVintage").value||0)]}
function renderCandidates(rankings){state.rankings=rankings;const sheet=$("candidateSheet");sheet.innerHTML="";for(const row of rankings){const card=document.createElement("button");card.type="button";card.className="candidate-card";card.innerHTML=`<img loading="lazy" src="${fileUrl(row.tile.local_path)}" alt="Candidate tile rank ${row.rank}"><strong>#${row.rank} · ${row.score.toFixed(4)}</strong><span>${row.tile.representation} · ${row.tile.scale}×</span>`;card.addEventListener("click",()=>selectCandidate(row,card));sheet.append(card)}if(!rankings.length)sheet.innerHTML="<p>No candidate tiles were ranked.</p>"}
function selectCandidate(row,card){document.querySelectorAll(".candidate-card").forEach(node=>node.classList.remove("selected"));card?.classList.add("selected");state.selected=row;$("tilePreview").src=fileUrl(row.tile.local_path);if(state.tileLayer)state.tileLayer.remove();if(state.tileImage)state.tileImage.remove();state.tileLayer=L.geoJSON(row.tile.physical_footprint,{style:{color:"#ffb45c",weight:3,fillOpacity:.04}}).addTo(map);map.fitBounds(state.tileLayer.getBounds(),{padding:[40,40]});const bounds=state.tileLayer.getBounds();state.tileImage=L.imageOverlay(fileUrl(row.tile.local_path),bounds,{opacity:Number($("overlayOpacity").value),interactive:false}).addTo(map);log("Candidate selected",{rank:row.rank,tile_id:row.candidate_tile_id})}
function renderMatch(candidate){state.match=candidate;$("homographyJson").value=JSON.stringify(candidate.homography,null,2);$("cornerJson").value=JSON.stringify(candidate.proposed_image_corners,null,2);const inliers=candidate.inlier_mask||[];$("correspondences").innerHTML=(candidate.matches||[]).map((item,index)=>`<div class="match-row ${inliers[index]?"inlier":"rejected"}"><b>${inliers[index]?"INLIER":"REJECT"}</b><span>${item.source.map(v=>v.toFixed(1)).join(",")} → ${item.destination.map(v=>v.toFixed(1)).join(",")} · d=${item.distance.toFixed(2)}</span></div>`).join("")||"No usable correspondences.";const m=candidate.metrics;$("registrationMetrics").innerHTML=`<span>Control fit RMSE<br><strong>${m.reprojection_rmse_px?.toFixed?.(2)??m.reprojection_rmse_px} px</strong></span><span>Held-out checkpoints<br><strong>not yet tested</strong></span><span>Preliminary uncertainty<br><strong>${candidate.preliminary_uncertainty_m??"unknown"} m</strong></span>`}
function currentCandidate(){if(!state.match)throw new Error("Match a candidate first");return {...state.match,homography:parse("homographyJson"),proposed_image_corners:parse("cornerJson")}}
function checkpointIcon(label){return L.divIcon({className:"checkpoint-marker",html:label,iconSize:[26,26]})}
function refreshCheckpoints(){checkpointLayer.clearLayers();state.checkpoints=parse("checkpointsJson",[]);state.checkpoints.forEach((p,i)=>L.marker([p.map_coordinate[1],p.map_coordinate[0]],{icon:checkpointIcon(`C${i+1}`)}).addTo(checkpointLayer).bindTooltip(p.description||p.landmark_id))}
function reviewDraft(){const rightsStatus=$("rightsStatus").value;const evidence=[state.match?.source_image_sha256,state.validation?.sha256].filter(value=>/^[a-f0-9]{64}$/.test(value||""));return {reviewer:$("reviewer").value.trim(),decision:$("decision").value,selected_candidate_id:state.match?.registration_candidate_id||null,edited_controls:parse("controlsJson",[]),held_out_checkpoints:parse("checkpointsJson",[]),spatial_classification:$("classification").value,coordinate_uncertainty_m:$("uncertainty").value===""?null:Number($("uncertainty").value),rights_decision:{status:rightsStatus,holder:$("rightsHolder").value.trim()||null,license:$("license").value.trim()||null,proof:$("rightsProof").value.trim()||null,public_derivative_export_allowed:$("derivativeAllowed").checked},publication_eligible:$("publicationEligible").checked,notes:$("reviewNotes").value,evidence_sha256s:[...new Set(evidence)],compatible_evidence_types:$("evidenceTypes").value.split(",").map(x=>x.trim()).filter(Boolean),contradictory_evidence_unresolved:false,source_coordinate_method:$("coordinateMethod").value.trim()||null}}
function renderRights(){const status=$("rightsStatus").value;const allowed=$("derivativeAllowed").checked&&["public_domain","cc0","cc_by","cc_by_sa","permission_granted"].includes(status)&&$("rightsProof").value.trim();$("rightsNotice").className=`rights-notice ${allowed?"allowed":"denied"}`;$("rightsNotice").textContent=allowed?"A rights claim and proof are recorded; the backend still revalidates publication export.":"Local analysis only. Public derivatives fail closed until rights status, proof, holder/license where required, and explicit authorization are recorded."}

async function connectWorker(){try{const result=await request("/health");setConnection(true,`Connected to local worker · cache ${result.cache_root} · no credentials exposed to browser`);log("API connection",result);return result}catch(error){setConnection(false,"Local geolocation worker not connected");log("API connection unavailable",{error:error.message,public_page:location.protocol==="https:"});return null}}
$("connectApi").addEventListener("click",connectWorker);
let searchTimer;$("formationSearch").addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{if(!state.connected)return;const result=await request(`/formations?q=${encodeURIComponent($("formationSearch").value)}&limit=30`);$("formationResults").innerHTML=result.items.map(f=>`<button type="button" class="search-result" data-id="${f.formation_id}">${f.date_iso||f.year} — ${f.place||"unnamed"}<small>${f.region||""}, ${f.country||""} · ${f.site_status}</small></button>`).join("");document.querySelectorAll(".search-result").forEach(button=>button.addEventListener("click",()=>{$("formationId").value=button.dataset.id;$("loadFormation").click()}))},220)});
$("loadFormation").addEventListener("click",()=>action("Formation loaded",async()=>{const result=await request(`/formations/${encodeURIComponent($("formationId").value.trim())}`);renderContext(result);return result}));
$("createJob").addEventListener("click",()=>action("Job created",async()=>{const result=await request("/jobs",{method:"POST",body:JSON.stringify({formation_id:$("formationId").value.trim()})});renderJob(result);return {job_id:result.job.job_id,state:result.job.state}}));
$("loadJob").addEventListener("click",()=>action("Job loaded",async()=>{const result=await request(`/jobs/${encodeURIComponent($("jobId").value.trim())}`);renderJob(result);if(result.job.search_polygons?.length){const geometry=result.job.search_polygons.at(-1).geometry;$("searchPolygon").value=JSON.stringify(geometry,null,2);showSearchPolygon(geometry)}return result}));
$("saveClues").addEventListener("click",()=>action("Clues saved",async()=>{const result=await request(`/jobs/${state.job.job_id}/clues`,{method:"POST",body:JSON.stringify({clues:parse("cluesJson",[])})});renderJob(result);return result}));
$("useMapBounds").addEventListener("click",()=>{const geometry=polygonFromBounds();$("searchPolygon").value=JSON.stringify(geometry,null,2);showSearchPolygon(geometry)});
$("saveSearchArea").addEventListener("click",()=>action("Search area saved",async()=>{const geometry=parse("searchPolygon");const result=await request(`/jobs/${state.job.job_id}/search-area`,{method:"POST",body:JSON.stringify({geometry,exclusions:parse("exclusionsJson",[]),provider:"reviewer_map",query:"reviewer-defined bounded search"})});renderJob(result);showSearchPolygon(geometry);return result}));
$("searchImagery").addEventListener("click",()=>action("Imagery searched",async()=>{const provider=$("provider").value;const location=$("providerLocation").value.trim();const options=provider==="local_raster"?{raster_root:location}:provider==="usgs_m2m"?{dataset_name:$("collection").value.trim()}:{endpoint:location||undefined};const result=await request(`/jobs/${state.job.job_id}/imagery/search`,{method:"POST",body:JSON.stringify({provider,provider_options:options,collections:$("collection").value.trim()?[$("collection").value.trim()]:null,date_start:$("dateStart").value||null,date_end:$("dateEnd").value||null})});renderImagery(result);renderJob(await request(`/jobs/${state.job.job_id}`));return {item_count:result.item_count,path:result.path}}));
$("generateTiles").addEventListener("click",()=>action("Tiles generated",async()=>{const result=await request(`/jobs/${state.job.job_id}/tiles`,{method:"POST",body:JSON.stringify({imagery_item:selectedImagery(),tile_size_m:Number($("tileSize").value),overlap:Number($("tileOverlap").value),scales:[1],rotations:[0],representations:["color","edge","gradient"]})});state.tileManifest=await request(`/artifact?path=${encodeURIComponent(result.path)}`);renderJob(await request(`/jobs/${state.job.job_id}`));return {tile_count:result.tile_count,cache_hits:result.cache_hits,path:result.path}}));
$("sourceImageFile").addEventListener("change",event=>{const file=event.target.files[0];if(file){$("sourcePreview").src=URL.createObjectURL(file);log("Browser-local source preview loaded",{name:file.name,size:file.size,uploaded:false})}});
$("rankTiles").addEventListener("click",()=>action("Tiles ranked",async()=>{if(!state.tileManifest)throw new Error("Generate tiles first");const result=await request(`/jobs/${state.job.job_id}/rank`,{method:"POST",body:JSON.stringify({source_image_path:$("sourceImagePath").value.trim(),tile_manifest:state.tileManifest,top_k:Number($("topK").value)})});renderCandidates(result.rankings);renderJob(await request(`/jobs/${state.job.job_id}`));return {ranked:result.rankings.length,path:result.path}}));
$("matchCandidate").addEventListener("click",()=>action("Candidate matched",async()=>{if(!state.selected)throw new Error("Select a candidate tile first");const result=await request(`/jobs/${state.job.job_id}/match`,{method:"POST",body:JSON.stringify({source_image_path:$("sourceImagePath").value.trim(),tile:state.selected.tile,retrieval_score:state.selected.score})});renderMatch(result.candidate);renderJob(await request(`/jobs/${state.job.job_id}`));return {candidate_id:result.candidate.registration_candidate_id,status:result.candidate.machine_status,inliers:result.candidate.metrics.inlier_count,path:result.path}}));
$("overlayOpacity").addEventListener("input",()=>state.tileImage?.setOpacity(Number($("overlayOpacity").value)));
$("addCheckpoint").addEventListener("click",()=>{state.checkpointMode=true;$("mapHint").textContent="Click the matching stable landmark on the map; you will then enter its source-image pixel."});
map.on("click",event=>{if(!state.checkpointMode)return;const x=Number(prompt("Source-image pixel X for this held-out checkpoint:"));const y=Number(prompt("Source-image pixel Y for this held-out checkpoint:"));if(!Number.isFinite(x)||!Number.isFinite(y))return;const item={landmark_id:`checkpoint_${Date.now()}`,role:"checkpoint",description:prompt("Stable landmark description:","road intersection")||"stable landmark",source_pixel:[x,y],map_coordinate:[event.latlng.lng,event.latlng.lat],reference_imagery_id:selectedImagery()?.imagery_item_id||"review-map",landmark_uncertainty_m:5};const values=parse("checkpointsJson",[]);values.push(item);$("checkpointsJson").value=JSON.stringify(values,null,2);state.checkpointMode=false;refreshCheckpoints();log("Held-out checkpoint added",item)});
$("validateRegistration").addEventListener("click",()=>action("Registration validated",async()=>{const candidate=currentCandidate();const result=await request(`/jobs/${state.job.job_id}/validate`,{method:"POST",body:JSON.stringify({registration_candidate_id:candidate.registration_candidate_id,controls:parse("controlsJson",[]),held_out_checkpoints:parse("checkpointsJson",[]),reviewer:$("reviewer").value.trim()})});state.validation=result.validation;$("uncertainty").value=result.validation.uncertainty.coordinate_uncertainty_m;const m=result.validation.metrics;$("registrationMetrics").innerHTML=`<span>Control fit<br><strong>${candidate.metrics.reprojection_rmse_px.toFixed(2)} px</strong></span><span>Checkpoint median / RMSE / max<br><strong>${m.median_m} / ${m.rmse_m} / ${m.maximum_m} m</strong></span><span>Conservative uncertainty<br><strong>${result.validation.uncertainty.coordinate_uncertainty_m} m</strong></span>`;return {result:result.validation.result,metrics:m,path:result.path}}));
$("saveReview").addEventListener("click",()=>action("Review decision saved",async()=>{const result=await request(`/jobs/${state.job.job_id}/review`,{method:"POST",body:JSON.stringify({review:reviewDraft(),checkpoint_validation:state.validation})});state.review=result.review;renderJob(await request(`/jobs/${state.job.job_id}`));return {review_id:result.review.review_id,state:result.state,publication:result.publication,path:result.path}}));
$("exportReview").addEventListener("click",()=>download(`${$("formationId").value}-field-resolution-review.json`,state.review||reviewDraft()));
$("generateKmz").addEventListener("click",()=>action("Local overlay generated",async()=>{if(!state.review)throw new Error("Save a review decision first");const result=await request(`/jobs/${state.job.job_id}/overlay`,{method:"POST",body:JSON.stringify({review:state.review,registration_candidate:currentCandidate(),tile:state.selected.tile,source_image_path:$("sourceImagePath").value.trim(),public_export:false})});$("openKmz").disabled=false;$("openKmz").dataset.path=result.overlay.kmz_path;return result.overlay}));
$("openKmz").addEventListener("click",()=>window.open(fileUrl($("openKmz").dataset.path),"_blank","noopener"));
for(const id of ["rightsStatus","rightsProof","rightsHolder","license","derivativeAllowed"]){$(id).addEventListener("input",renderRights)}
renderRights();connectWorker();
